"""Generate paper tables and a readable results ledger from recorded data only."""
from pathlib import Path
import json
R=Path(__file__).resolve().parents[1]
s=json.loads((R/'artifacts/v4/heldout/latent_summary.json').read_text())
d=json.loads((R/'artifacts/v4/latent_diagnostics.json').read_text())
labels={'anchor':'Fixed anchor','full_history_optimistic':'Full-history planner','last_output_model':'Last-output model',
'latent_neural_B0':'Witness, $B=0$','latent_neural_B16':'Witness, $B=16$',
'latent_neural_B64':'Witness, $B=64$','latent_untrained_B64':'No neural training, $B=64$',
'latent_unguided_B64':'Unguided probes, $B=64$'}
t=['% Auto-generated by tools/v4_tables.py from recorded held-out results.',
 r'\begin{tabular}{lrrr}',r'\toprule',r'System & Mean & Late A & Max. deficit \\',r'\midrule']
md=['# v0.4 executed results','',s['status']+'.','',
'100 fresh seeds, 48 episodes, eight systems, 38,400 episode rows. The hidden table is stationary; the public objective follows A-B-A. Episode rewards range from 0 to 8. “Late A” averages the last eight episodes. Deficit is the worst completed-episode prefix relative to the same fixed anchor, maximized across seeds.','',
'| System | Mean return | Late A | Maximum prefix deficit |','|---|---:|---:|---:|']
for a in s['aggregates']:
 l=labels[a['method']];m=a['mean_return']['mean'];v=a['late_A']['mean'];x=a['max_worst_prefix_deficit']
 t.append(f'{l} & {m:.4f} & {v:.4f} & {x:g} '+r'\\')
 md.append(f'| {l.replace("$","")} | {m:.4f} | {v:.4f} | {x:g} |')
t+= [r'\bottomrule',r'\end{tabular}']
(R/'paper/v4_results.tex').write_text('\n'.join(t)+'\n')
md+=['','## Primary paired comparison','']
for p in s['paired_vs_full_history']:
 if p['method']=='latent_neural_B16':
  md.append(f"Witness B16 minus full-history planner: {p['mean_difference']:.8f} reward per episode, paired-seed 95% t interval [{p['ci95_t'][0]:.8f}, {p['ci95_t'][1]:.8f}]. This is a negative result on prequential mean return, not benchmark superiority.")
md+=['','## Scope and proof status','',
'Zero incumbent regressions were observed in the realizable deterministic study. This protects reset values for the two declared objectives, not all deployed actions, hidden drift, or arbitrary natural-language tasks. The full-history planner is symbolic and is not raw-history LLM ICL.',
'', '355 Python tests pass. An additional 400 C++ paired-program cases plus a reward-range rejection pass under UBSan; 632 legacy C++ cases plus an overflow check also pass. Fifty Lean declarations are attempts, none kernel-checked in this environment. No native CL-Bench/AgentCL, local LLM inference, or new GPU kernel was executed.',
'','See `holdout_audit.json`, `latent_diagnostics.json`, raw compressed episode files, and `docs/v4/` for provenance and boundaries.']
(R/'artifacts/v4/RESULTS.md').write_text('\n'.join(md)+'\n')
print('wrote paper/v4_results.tex and artifacts/v4/RESULTS.md')
